### ISSUE TITLE
使用最新的kube-flannel.yml后Pod coredns一直都是pending状态

### ISSUE THREAD

**Issue by airbadboy-victor** [xiaopeng163/learn-k8s-from-scratch#16]
章节[kubeadm](https://learn-k8s-from-scratch.readthedocs.io/en/latest/k8s-install/kubeadm.html#)，使用最新的https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml，这个yml文件创建的Pod kube-flannel-ds使用的name space从kube-system修改为kube-flannel，而且在旧版的kube-flannel.yml里的PodSecurityPolicy，在新版里也被删除了，使用最新的yml文件的效果就是coredns一致处于pending状态（如下）。请帮忙看一下如何应用最新的yml文件，实现文档里的功能，感谢！
-------------------------------------------------------------------------------------------------------
[root@k8s]# kubectl get pod -A
NAMESPACE      NAME                                                                   READY   STATUS    RESTARTS   AGE
kube-flannel   kube-flannel-ds-9kzgs                                                  1/1     Running   0          2d15h
kube-system    coredns-5d78c9869d-9ln7c                                               0/1     Pending   0          2d19h
kube-system    coredns-5d78c9869d-ndf89                                               0/1     Pending   0          2d19h
kube-system    etcd-us1a-eng-zhliang-hub01.nprd.temp.com                      1/1     Running   5          2d19h
kube-system    kube-apiserver-us1a-eng-zhliang-hub01.nprd.temp.com            1/1     Running   5          2d19h
kube-system    kube-controller-manager-us1a-eng-zhliang-hub01.nprd.temp.com   1/1     Running   3          2d19h
kube-system    kube-proxy-9sgfg                                                       1/1     Running   0          2d19h
kube-system    kube-scheduler-us1a-eng-zhliang-hub01.nprd.temp.com            1/1     Running   5          2d19h
-------------------------------------------------------------------------------------------------------

**Comment by xiaopeng163** [comment]
https://learn-k8s-from-scratch.readthedocs.io/en/latest/k8s-install/kubeadm.html

please try with v1.29, the current latest update

**Comment by ylka** [comment]
用最新的也遇到这个问题，是不是 name space 不一样的问题？

**Comment by ylka** [comment]
我这边重启了 master 然后可以了
