### ISSUE TITLE
kubeadm集群安装报错

### ISSUE THREAD

**Issue by cryboy007** [xiaopeng163/learn-k8s-from-scratch#17]
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

**Comment by xiaopeng163** [comment]
请问具体是哪一步出现的问题？

**Comment by cryboy007** [comment]
> 请问具体是哪一步出现的问题？

我解决了,国内网络的问题, kubeadm init --image-repository registry.aliyuncs.com/google_containers 指定阿里云镜像后,还需要修改:/etc/containerd/config.toml,sandbox_image = "xxx/pause:3.6" 也需要改为阿里云云镜像仓库

**Comment by Wwwmmxxx** [comment]
太感谢啦, 解决了问题.
