### ISSUE TITLE
v1.28 国内 kubeadm init 失败的问题

### ISSUE THREAD

**Issue by zhaozhong** [xiaopeng163/learn-k8s-from-scratch#22]
老师好，在国内 init 时会卡住，查看错误日志发现是 containerd 会从 registry.k8s.io/pause:3.6 拉取镜像，而国内网络环境无法访问这个地址。

相信国内的很多同学会碰到这个问题，课程可以收录关于此问题的解决。

解决办法详见：https://github.com/kubernetes/kubeadm/issues/2851#issuecomment-1535770518

**Comment by chenkewen2007** [comment]
是的。我也发现了此问题。也可以在 echo "[TASK 5] Install containerd runtime"内进行修改,在创建配置文件时候直接替换

在老师的脚本中，加入以下行：
sed -i 's/registry.k8s.io\/pause:3.6/registry.aliyuncs.com\/google_containers\/pause:3.9/g' /etc/containerd/config.toml 


```
echo "[TASK 5] Install containerd runtime"
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt -qq update >/dev/null 2>&1
apt install -qq -y containerd.io >/dev/null 2>&1
containerd config default >/etc/containerd/config.toml
sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
sed -i 's/registry.k8s.io\/pause:3.6/registry.aliyuncs.com\/google_containers\/pause:3.9/g' /etc/containerd/config.toml 
systemctl restart containerd
systemctl enable containerd >/dev/null 2>&1
```

**Comment by xiaopeng163** [comment]
您好，非常感谢，可以帮提个PR么，谢谢🙏

**Comment by xiaopeng163** [comment]
> 是的。我也发现了此问题。也可以在 echo "[TASK 5] Install containerd runtime"内进行修改,在创建配置文件时候直接替换
> 
> 在老师的脚本中，加入以下行： sed -i 's/registry.k8s.io/pause:3.6/registry.aliyuncs.com/google_containers/pause:3.9/g' /etc/containerd/config.toml
> 
> ```
> echo "[TASK 5] Install containerd runtime"
> mkdir -p /etc/apt/keyrings
> curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
> echo   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
> $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
> apt -qq update >/dev/null 2>&1
> apt install -qq -y containerd.io >/dev/null 2>&1
> containerd config default >/etc/containerd/config.toml
> sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
> sed -i 's/registry.k8s.io\/pause:3.6/registry.aliyuncs.com\/google_containers\/pause:3.9/g' /etc/containerd/config.toml 
> systemctl restart containerd
> systemctl enable containerd >/dev/null 2>&1
> ```
您好，非常感谢，可以帮提个PR么，谢谢🙏
