### ISSUE TITLE
中国大陆版教程中kubeadm init 失败

### ISSUE THREAD

**Issue by peng-yq** [xiaopeng163/learn-k8s-from-scratch#30]
需要把/etc/containerd/config.toml中的sandbox_image = "k8s.gcr.io/pause:3.6"  --> sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.9"  ，不让在启动的时候一直去拉前者，电脑无法访问registry.k8s.io的时候就会一直访问失败，可以在教程中添加一下

**Comment by peng-yq** [comment]
> 需要把/etc/containerd/config.toml中的sandbox_image = "k8s.gcr.io/pause:3.6" --> sandbox_image = "registry.aliyuncs.com/google_containers/pause:3.9" ，不让在启动的时候一直去拉前者，电脑无法访问registry.k8s.io的时候就会一直访问失败，可以在教程中添加一下

master和worker都需要改

**Comment by xiaopeng163** [comment]
应该改了吧？https://learn-k8s-from-scratch.readthedocs.io/en/latest/k8s-install/kubeadm-cn.html

我前几天还做过一期视频演示在阿里云上部署 https://www.bilibili.com/video/BV1xr421H7aj/
