### ISSUE TITLE
gcr.io/google-samples.hello-app:1.0 ErrPullImage

### ISSUE THREAD

**Issue by Wwwmmxxx** [xiaopeng163/learn-k8s-from-scratch#31]
在 `kubectl service` 章节, 会使用到 `image:gcr.io/google-samples/hello-app:1.0`
由于国内网络问题, `get pod`命令后报错 `ErrPullImage`
搜索后, 可使用 `anjia0532/google-samples.hello-app:1.0` 作为替换继续学习

**Comment by xiaopeng163** [comment]
感谢提醒，我更新了下文档，另外我在我自己的dockerhub里也备份了一下  `xiaopeng163/hello-app:1.0`
