### ISSUE TITLE
kubeadm的containerd安装改善

### ISSUE THREAD

**Issue by ych0537** [xiaopeng163/learn-k8s-from-scratch#9]
安装脚本中
https://github.com/xiaopeng163/learn-k8s-from-scratch/blob/master/source/k8s-install/kubeadm.rst
的containerd 安装相关。
[echo "[TASK 5] Install containerd runtime"](https://github.com/xiaopeng163/learn-k8s-from-scratch/blob/master/source/k8s-install/kubeadm.rst#:~:text=echo%20%22%5BTASK%205%5D%20Install%20containerd%20runtime%22)
按照脚本可以正常安装，但是ubuntu20.04默认安装的是1.5.9版本，跟kubeadm的1.24不匹配。
导致后面初始化master节点会失败。
（猜想是这么长时间，kubeadm小版本升级导致跟containerd不匹配。）

按照脚本改造成下面就ok了。

```
echo "[TASK 5] Install containerd runtime"
apt update -qq >/dev/null 2>&1
apt install -qq -y  apt-transport-https >/dev/null 2>&1
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
sudo mkdir -m 0755 -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt remove containerd
apt update
apt install containerd.io
rm /etc/containerd/config.toml
systemctl enable containerd
systemctl restart containerd
```

**Comment by xiaopeng163** [comment]
非常感谢，我也发现了这个问题， https://serverfault.com/questions/1118051/failed-to-run-kubelet-validate-service-connection-cri-v1-runtime-api-is-not-im

我会更新一下文档
